server:
  port: 8080

logging:
  level:
    org.springframework.amqp: DEBUG
    com.kickoff: DEBUG

spring:
  application:
    name: membership-service

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/membership_service?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guestuser
    password: guestuser

  data:
    redis:
      host: localhost
      port: 6379

value:
  jwt:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest