server:
  port: 8080

logging:
  level:
    com.kickoff: DEBUG

spring:
  application:
    name: membership-service

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/kickoff
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root