server:
  port: 8082

logging:
  level:
    org.springframework.amqp: DEBUG
    com.kickoff: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: match-service

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        type:
          org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  datasource:
    url: jdbc:postgresql://localhost:5432/match_service?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guestuser
    password: guestuser
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql

value:
  rapid:
    api:
      key: ${RapidApiKey}
  jwt:
    secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
